### ISSUE TITLE
Required Repositories not Symlinking Correctly..

### ISSUE THREAD

**Issue by brandontamm** [AOEpeople/composer-installers#2]
Problem: Composer clones my “require”d repos to the vendor directory, but is not symlinking them into the Magento core files.

Background: I am using the setup at https://github.com/andreaskoch/dockerized-magento. The modules that Andreas had listed there are correctly symlinking. The magento core that i added installs correctly and works just fine, but the three other repos I added are not. The repos are connected to packagist via github. My Magento core is installing correctly, but the two modules and the one theme repo is not. My composer.json is here: http://pastebin.com/gTpKQy8K#

Solution: Can you help? :-)

**Comment by drobinson** [comment]
Looks like your modules are missing the modman file which defines where the symlinking should be done - check this one as an example: https://github.com/AOEpeople/Aoe_Scheduler/blob/master/modman

Modman documentation: https://github.com/colinmollenhour/modman/wiki/Tutorial
